# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyblog', '0004_auto_20190408_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='author',
            name='qq',
        ),
    ]
